title: Beh Yit Han
description: XMUM Student
show_downloads: true
theme: jekyll-theme-minimal
github:
  zip_url: https://github.com/YHBeh/yhbeh.github.io/blob/main/Generic-Format-for-Research-Project-Paper.pdf
